### ISSUE TITLE
Docker target how to use init script

### ISSUE THREAD

**Issue by rpignolet** [roboconf/roboconf.github.io#45]
There is a problem since Docker 1.0.1 with the command `start-stop-daemon` (which is used by almost all init scripts) with the `--exec` option due to a permission denied because it need to access to `/proc/%d/exec` but the `SYS_PTRACE` permission is required.

1. A solution is to add a line in Roboconf recipe deploy script which replace the `--exec` option by `--startas`. A `sed` command can do the job:
`sed -i 's/--exec/--startas/g' /etc/init.d/service`

2. Or a solution which need a change in Roboconf is the docker command which run the image. Add the option `--cap-add SYS_PTRACE` like:
`docker run --cap-add SYS_PTRACE -p 8080:8080 tomcat`

The second solution allow to modify only the docker command and do not change recipe scripts. If I well understand the `SYS_PTRACE` permission it allow a process to examine the memory and running state of other processes. (Source: http://lwn.net/Articles/393010/) I think that in production it is a bad idea to allow this.

Source and more details:
http://blog.deliverous.com/2015-01-03.start-stop-daemon.html
https://chris-lamb.co.uk/posts/start-stop-daemon-exec-vs-startas

For example the Tomcat7 init script use `--exec` option so all recipe that install Tomcat with package manager and run it with init script will fail in Docker. Note that the service is correctly launched, the problem is when the script want to check if the processus is launched.

I tested the first solution with https://github.com/roboconf/roboconf-examples/tree/master/apache-tomcat-bash and it works. I just have to add this line:
`sed -i 's/--exec/--startas/g' /etc/init.d/tomcat7`
in the file `apache-tomcat-bash/src/main/model/graph/Tomcat/scripts/deploy.sh` at line 5.

But normaly when you install a Tomcat the service is started automatically after the installation and in theory the Tomcat server will be launched. But in the ubuntu docker image the Policy layer return always 101 which means that nothing will be start or upgrade after installation via package manager.
Source: http://askubuntu.com/questions/365911/why-the-services-do-not-start-at-installation
So you can install Tomcat7, do what ever you want in init script because the service is not launched.

**Comment by vincent-zurczak** [comment]
See roboconf/roboconf-platform#335
We will also report this on the web site, in the Docker sections.
