### ISSUE TITLE
Change our « slogan »

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf.github.io#84]
From the beginning of the project, we have kept **a solution for elastic deployments**. But we have also known, for quite a long time, that Roboconf is not a deployment solution, it goes beyond. I suggest we replace it by **Making and Managing Elastic Applications**.

Followed by « In cloud. On premise. With packages. With containers. With whatever you want. »
Any comment or suggestion? @donsez @gibello @depalman @diarraa @cdeneux

**Comment by vincent-zurczak** [comment]
> Not so bad, but I'm not sure of the meaning of "Making" here (do we "make applications" ? or is it
> "assembling" or "setting up" or something else we used to call "deploying" ??)

Or we could just use **a solution for elastic applications**.

**Comment by cdeneux** [comment]
Don't forget the side 'deployment'. My proposal: **Making, Deploying and Managing Elastic Applications**

**Comment by cdeneux** [comment]
Another slogan: **From cloud-ready to cloud reallity**

**Comment by vincent-zurczak** [comment]
Cloud is important. But we also worked a lot lately to be as efficient as possible with on-premise servers. So, we would like something more open and less restrictive. ;)

**Comment by vincent-zurczak** [comment]
Note for later: describe, deploy, scale, repair, migrate.

**Comment by vincent-zurczak** [comment]
OK, here is an attempt.
I tried to put as much information as possible in a minimal amount of space.

* FR: http://roboconf.net/fr/index.html
* EN: http://roboconf.net/en/index.html

Feel free to comment or complaint. :man_dancing:
